[package]
name = "rcgen"
version = "0.3.1"
authors = ["est31 <MTest31@outlook.com>"]
description = "Rust X.509 certificate generator"
repository = "https://github.com/est31/rcgen"
documentation = "https://docs.rs/rcgen"
license = "MIT/Apache-2.0"
readme = "README.md"

[lib]
name = "rcgen"
path = "src/lib.rs"

[[bin]]
name = "rcgen"
path = "src/main.rs"

[dependencies]
yasna = { version = "0.3.0", features = ["chrono", "bit-vec"] }
bit-vec = "0.6.1"
ring = "0.14"
untrusted = "0.6"
pem = { version = "0.6", optional = true }
chrono = "0.4.6"
x509-parser = { version = "0.4.1", optional = true }

[features]
default = ["pem"]

[dev-dependencies]
openssl = "0.10"
webpki = "0.19"
